version: '3'

services:
    # db:
    #     image: postgres
    #     environment:
    #         - POSTGRES_DB=playground
    #         - POSTGRES_USER=postgres
    #         - POSTGRES_PASSWORD=ehwns0910
    web:
        build: .
        # command: gunicorn /code/playground.wsgi:application --bind 0.0.0.0:8000
        # &&gunicorn config.wsgi:application --bind=0.0.0.0:8000"
        # &&python manage.py runserver"
        command: >
            bash -c "python manage.py makemigrations
            && python manage.py migrate
            && gunicorn pgbackend.wsgi:application --bind=0.0.0.0:8000"
        volumes:
            - .:/web
        expose:
            - 8000
        # depends_on:
        #     - db
        env_file:
            - .env.production
    nginx:
        image: nginx
        # build: ./config/nginx
        volumes: 
            - ./nginx:/etc/nginx/conf.d
            - ./staticfiles:/web/staticfiles
        ports:
            - 80:80
        depends_on: 
            - web
