# Generated by Django 3.0.5 on 2020-08-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200810_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.URLField(max_length=300),
        ),
    ]
