# Generated by Django 3.0.5 on 2020-08-29 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_auto_20200805_1225'),
        ('items', '0003_auto_20200810_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tanning_method', models.IntegerField(choices=[(0, 'Vegetable'), (1, 'Chrome'), (2, 'Hybrid')])),
                ('explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tannery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('nationality', models.CharField(max_length=100)),
                ('explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LeatherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('note', models.TextField()),
                ('leather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Leather')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Store')),
            ],
        ),
        migrations.AddField(
            model_name='leather',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Material'),
        ),
        migrations.AddField(
            model_name='leather',
            name='tanery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Tannery'),
        ),
    ]
