# Generated by Django 3.0.5 on 2020-08-30 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_auto_20200805_1225'),
        ('items', '0004_auto_20200830_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leather',
            old_name='tanery',
            new_name='tannery',
        ),
        migrations.AlterField(
            model_name='leatherdetail',
            name='store',
            field=models.ForeignKey(limit_choices_to={'category': 2}, on_delete=django.db.models.deletion.CASCADE, to='stores.Store'),
        ),
    ]
