# Generated by Django 3.0.5 on 2020-08-30 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20200830_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leatherdetail',
            name='leather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leather_details', to='items.Leather'),
        ),
    ]
