# Generated by Django 3.1 on 2020-09-03 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0007_auto_20200830_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='leather',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leatherdetail',
            name='sellingPageUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tannery',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.IntegerField(choices=[(0, 'Tannery'), (1, 'Material'), (2, 'Leather'), (3, 'LeatherDetail')])),
                ('fk', models.IntegerField()),
                ('writer_name', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.JSONField()),
                ('deleted', models.BooleanField(default=False)),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
