# Generated by Django 3.1 on 2020-09-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20200907_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leather',
            name='tannery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.tannery'),
        ),
    ]
