# Generated by Django 3.0.5 on 2020-07-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('latlng', models.CharField(max_length=191)),
                ('address', models.CharField(max_length=191)),
                ('category', models.IntegerField(choices=[(0, 'workshop'), (1, 'toolStore'), (2, 'leatherStore'), (4, 'materialStore')])),
                ('homepage', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
            ],
        ),
    ]
