# Generated by Django 3.0.5 on 2020-07-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='blog',
            field=models.URLField(null=True),
        ),
    ]
