# Generated by Django 3.0.5 on 2020-07-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='blog',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='homepage',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='instagram',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
