# Generated by Django 3.0.5 on 2020-07-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20200720_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='x',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='y',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
