# Generated by Django 3.0.5 on 2020-07-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20200722_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='latlng',
        ),
    ]
