# Generated by Django 3.0.5 on 2020-07-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_remove_store_latlng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.IntegerField(choices=[(0, 'workshop'), (1, 'toolStore'), (2, 'leatherStore'), (3, 'commonStore'), (4, 'materialStore')]),
        ),
    ]
