# Generated by Django 3.0.5 on 2020-08-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20200731_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='blog',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='homepage',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='instagram',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
